language: python
dist: xenial
sudo: required


notifications:
  irc:
    channels:
      - "irc.uvt.nl#gitlama"
    template:
      - "%{repository_slug}#%{build_number}-%{branch} : %{message} --> %{build_url}"
    skip_join: true

python:
    - 2.7
    - 3.4
    - 3.6
before_install:
    - pip install cython
install:
    - python setup.py install
script:
    - colibri-test
    - LD_LIBRARY_PATH="$VIRTUAL_ENV/lib/" python test.py
    - cd exp
    - LD_LIBRARY_PATH="$VIRTUAL_ENV/lib/" ./colibri-patternmodeller-test.sh

